// <auto-generated />
using System;
using Cooking.Service.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cooking.Service.DAL.Migrations
{
    [DbContext(typeof(CookingDbContext))]
    [Migration("20240304090642_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cooking.Service.DAL.Models.IngredientAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2,
                            IsDeleted = false,
                            Name = "Cucumber"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 2,
                            IsDeleted = false,
                            Name = "Olives"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 3,
                            IsDeleted = false,
                            Name = "Lettuce"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 6,
                            IsDeleted = false,
                            Name = "Meat"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 6,
                            IsDeleted = false,
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 8,
                            IsDeleted = false,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 10,
                            IsDeleted = false,
                            Name = "Dough"
                        });
                });

            modelBuilder.Entity("Cooking.Service.DAL.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Portions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2779),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2792),
                            Name = "Burger",
                            Portions = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2851),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2851),
                            Name = "Pie",
                            Portions = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2868),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2868),
                            Name = "Sandwich",
                            Portions = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2886),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2887),
                            Name = "Pasta",
                            Portions = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2954),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2954),
                            Name = "Salad",
                            Portions = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2990),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2990),
                            Name = "Pizza",
                            Portions = 4
                        });
                });

            modelBuilder.Entity("Cooking.Service.DAL.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2816),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2816),
                            Name = "Meat",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2824),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2825),
                            Name = "Lettuce",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2831),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2832),
                            Name = "Tomato",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 1,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2837),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2838),
                            Name = "Cheese",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 1,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2843),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2844),
                            Name = "Dough",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 2,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2857),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2857),
                            Name = "Dough",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 2,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2862),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2863),
                            Name = "Meat",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Amount = 1,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2874),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2874),
                            Name = "Dough",
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 9,
                            Amount = 1,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2880),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2881),
                            Name = "Cucumber",
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 10,
                            Amount = 2,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2892),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2893),
                            Name = "Dough",
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 11,
                            Amount = 1,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2898),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2898),
                            Name = "Tomato",
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 12,
                            Amount = 2,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2903),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2904),
                            Name = "Cheese",
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 13,
                            Amount = 1,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2946),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2947),
                            Name = "Meat",
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 14,
                            Amount = 2,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2960),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2961),
                            Name = "Lettuce",
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 15,
                            Amount = 2,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2966),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2967),
                            Name = "Tomato",
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 16,
                            Amount = 1,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2972),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2973),
                            Name = "Cucumber",
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 17,
                            Amount = 2,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2978),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2978),
                            Name = "Cheese",
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 18,
                            Amount = 1,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2984),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2985),
                            Name = "Olives",
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 19,
                            Amount = 3,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2996),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(2997),
                            Name = "Dough",
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 20,
                            Amount = 2,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(3002),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(3003),
                            Name = "Tomato",
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 21,
                            Amount = 3,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(3008),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(3008),
                            Name = "Cheese",
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 22,
                            Amount = 1,
                            CreatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(3013),
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2024, 3, 4, 11, 6, 42, 55, DateTimeKind.Local).AddTicks(3014),
                            Name = "Olives",
                            RecipeId = 6
                        });
                });

            modelBuilder.Entity("Cooking.Service.DAL.Models.RecipeIngredient", b =>
                {
                    b.HasOne("Cooking.Service.DAL.Models.Recipe", null)
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cooking.Service.DAL.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
